name: Scape latest data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '12 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
      - name: Fetch latest data
        run: |-
          curl -o map.pdf https://new.mta.info/map/5256
      - name: Commit and push if it changed
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest Patrol Guide: ${timestamp}" || exit 0
          git push
